name: YesodAppCurriculum

dependencies:
  - base >= 4.7 && < 5

default-extensions:
  - OverloadedStrings
  - DataKinds
  - DerivingStrategies
  - FlexibleInstances
  - GADTs
  - GeneralisedNewtypeDeriving
  - MultiParamTypeClasses
  - StandaloneDeriving
  - TypeFamilies
  - RecordWildCards
  - DeriveGeneric
  - DeriveAnyClass

library:
  source-dirs: library
  dependencies:
    - yesod
    - resource-pool
    - persistent-sqlite
    - monad-logger
    - persistent
    - text
    - aeson

executables:
  YesodAppCurriculum-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum

tests:
  YesodAppCurriculum-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum
