name: YesodAppCurriculum

default-extensions:
  - OverloadedStrings

dependencies:
  - base >= 4.7 && < 5

library:
  source-dirs: library
  dependencies:
    - yesod

executables:
  YesodAppCurriculum-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum

tests:
  YesodAppCurriculum-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum
