name: YesodAppCurriculum

dependencies:
  - base

default-extensions:
  - DataKinds
  - DeriveAnyClass
  - DeriveGeneric
  - DerivingStrategies
  - FlexibleInstances
  - GADTs
  - GeneralisedNewtypeDeriving
  - MultiParamTypeClasses
  - OverloadedStrings
  - RecordWildCards
  - StandaloneDeriving
  - TypeFamilies

library:
  source-dirs: library
  dependencies:
    - aeson
    - monad-logger
    - persistent
    - persistent-sqlite
    - resource-pool
    - text
    - time
    - yesod
    - yesod-core
    - case-insensitive
    - regex-tdfa
    # - regex-tdfa-text

executables:
  YesodAppCurriculum-exe:
    main: Main.hs
    source-dirs: app
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum

tests:
  YesodAppCurriculum-test:
    main: Spec.hs
    source-dirs: test
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - YesodAppCurriculum
